site_name: PyQuantumKit
site_description: A middleware for translating a quantum program into different quantum software stacks.
site_author: Peixun Long
site_url: https://github.com/hiquarc/PyQuantumKit/

plugins:
  - search
  # - i18n:
      #default_language: en
      # languages:
      #   - locale: en
      #     name: English
      #     link: /en/
      #     build: true
      #   - locale: zh
      #     name: 中文
      #     link: /zh/
      #     build: true
      #     default: true

theme:
  name: readthedocs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
# extra_css:
#   - css/extra.css

# Activate the LateX formula
markdown_extensions:
  # - pymdownx.superfences
  # - pymdownx.betterem:
  #     smart_enable: all
  # - pymdownx.caret
  # - pymdownx.critic
  # - pymdownx.details
  # - pymdownx.highlight
  # - pymdownx.inlinehilite
  # - pymdownx.keys
  # - pymdownx.mark
  # - pymdownx.smartsymbols
  # - pymdownx.superfences
  # - pymdownx.tasklist
  # - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 中文:
    - 首页: zh/index.md
    - 安装与使用: zh/getting-started.md
    - 稳定功能:
      - 跨平台量子线路构建: zh/stable/circuit.md
      - 量子线路矩阵的符号表示: zh/stable/symbol.md
    - API速查:
      - 量子开发框架速查: zh/api/supported-platforms.md
      - 量子门速查: zh/api/supported-gates.md
      - 量子线路构建API: zh/api/construct.md
      - CircuitIO类: zh/api/circuitio.md
      - 基于SymPy的符号表示: zh/api/symbol.md
    - 示例:
      - 带参数量子线路的符号表示及检验: zh/examples/z2.md
    - 实验性功能:
      - 实验性功能总览: zh/experimental/overall.md
      - 模块化构建: zh/experimental/construct.md
      - 量子哈密顿量模拟: zh/experimental/hsim.md
    - 版本历史: zh/changelog.md
  - English:
    - Home: en/index.md
